'use client';

import {
  LayoutGrid, Sparkles, Star, Zap, TrendingUp, Trophy,
  Flame, Heart, Crown, Rocket, Target, Shield, Gem,
  Award, Medal, Lightbulb, Brain, Cpu, Smartphone,
  Laptop, Headphones, Camera, Gamepad2, Music, Film,
  BookOpen, Newspaper, Megaphone, Bell, MessageSquare,
  Globe, Wifi, BarChart3, PieChart, Clock, Calendar,
  Layers, Grid3x3, Monitor, Tablet, Watch, Speaker,
  Code, Terminal, Database, Server, Cloud, Lock,
  Compass, Map, Flag, Gift, Package, ShoppingCart,
  Tag, Wallet, DollarSign, Users, GraduationCap, Briefcase,
  Building, Home, Palette, Brush, Hammer, CircleDot,
  Hexagon, Diamond, CheckCircle, Info, AlertCircle, Leaf,
  Mountain, Waves, Sun, Moon, Radio, Tv,
  Rss, Podcast, QrCode, Share2, Mail, Send,
  Paperclip, Link, ExternalLink, Copy, Printer,
  Settings, Wrench, Power, Plug, Battery, Bluetooth,
  Signal, Navigation, MapPin, Key, Ban, HelpCircle,
  XCircle, Play, Pause, SkipForward, SkipBack,
  Volume2, Mic, Video, FileText,
  Folder, Archive, Inbox, Reply, Forward,
  TrendingDown, ArrowUpRight, ArrowDown, ArrowLeft,
  ArrowRight, ChevronsRight, Move, Maximize, Minimize,
  ZoomIn, ZoomOut, Filter, SortAsc, SlidersHorizontal,
  RotateCcw, RefreshCw, Upload, Download,
  CloudRain, Thermometer, Wind, Droplets, TreePine,
  Umbrella, Flower2, TreeDeciduous, Dog, Cat, Bird,
  Fish, Bug, Pizza, Apple, Beef, IceCream,
  Coffee, Utensils, Factory, PiggyBank, Coins,
  BadgeCheck, UserCheck, UserPlus, PersonStanding,
  Scissors, PenTool, Ruler, Magnet,
  Anchor, Octagon, Triangle, Square, Pentagon,
  Cross, Minus, Equal, ChevronsLeft, ChevronsUp,
  ChevronsDown, BatteryCharging, BatteryFull, BatteryLow,
  BatteryMedium, CloudLightning, CloudMoon, CloudSun,
  Snowflake, Sunrise, Sunset, Rainbow,
  Rabbit, Squirrel, Cherry, Citrus, Grape,
  Banana, Egg, Cookie, Cake, Sandwich, Soup,
  Drum, Guitar, Piano,
  Clapperboard, Disc, Volume1, Hand, ThumbsUp,
  ThumbsDown, Smile, Frown, Skull, Ghost,
  PartyPopper, Timer, Hourglass, AlarmClock,
  Bookmark, BookmarkCheck, Box, Accessibility,
  Activity, Contact, IdCard, Scan, Fingerprint,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutGrid, Sparkles, Star, Zap, TrendingUp, Trophy,
  Flame, Heart, Crown, Rocket, Target, Shield, Gem,
  Award, Medal, Lightbulb, Brain, Cpu, Smartphone,
  Laptop, Headphones, Camera, Gamepad2, Music, Film,
  BookOpen, Newspaper, Megaphone, Bell, MessageSquare,
  Globe, Wifi, BarChart3, PieChart, Clock, Calendar,
  Layers, Grid3x3, Monitor, Tablet, Watch, Speaker,
  Code, Terminal, Database, Server, Cloud, Lock,
  Compass, Map, Flag, Gift, Package, ShoppingCart,
  Tag, Wallet, DollarSign, Users, GraduationCap, Briefcase,
  Building, Home, Palette, Brush, Hammer, CircleDot,
  Hexagon, Diamond, CheckCircle, Info, AlertCircle, Leaf,
  Mountain, Waves, Sun, Moon, Radio, Tv,
  Rss, Podcast, QrCode, Share2, Mail, Send,
  Paperclip, Link, ExternalLink, Copy, Printer,
  Settings, Wrench, Power, Plug, Battery, Bluetooth,
  Signal, Navigation, MapPin, Key, Ban, HelpCircle,
  XCircle, Play, Pause, SkipForward, SkipBack,
  Volume2, Mic, Video, FileText,
  Folder, Archive, Inbox, Reply, Forward,
  TrendingDown, ArrowUpRight, ArrowDown, ArrowLeft,
  ArrowRight, ChevronsRight, Move, Maximize, Minimize,
  ZoomIn, ZoomOut, Filter, SortAsc, SlidersHorizontal,
  RotateCcw, RefreshCw, Upload, Download,
  CloudRain, Thermometer, Wind, Droplets, TreePine,
  Umbrella, Flower2, TreeDeciduous, Dog, Cat, Bird,
  Fish, Bug, Pizza, Apple, Beef, IceCream,
  Coffee, Utensils, Factory, PiggyBank, Coins,
  BadgeCheck, UserCheck, UserPlus, PersonStanding,
  Scissors, PenTool, Ruler, Magnet,
  Anchor, Octagon, Triangle, Square, Pentagon,
  Cross, Minus, Equal, ChevronsLeft, ChevronsUp,
  ChevronsDown, BatteryCharging, BatteryFull, BatteryLow,
  BatteryMedium, CloudLightning, CloudMoon, CloudSun,
  Snowflake, Sunrise, Sunset, Rainbow,
  Rabbit, Squirrel, Cherry, Citrus, Grape,
  Banana, Egg, Cookie, Cake, Sandwich, Soup,
  Drum, Guitar, Piano,
  Clapperboard, Disc, Volume1, Hand, ThumbsUp,
  ThumbsDown, Smile, Frown, Skull, Ghost,
  PartyPopper, Timer, Hourglass, AlarmClock,
  Bookmark, BookmarkCheck, Box, Accessibility,
  Activity, Contact, IdCard, Scan, Fingerprint,
};

export function HeadingIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICON_MAP[name];
  if (!Icon) return <LayoutGrid className={className} />;
  return <Icon className={className} />;
}
